### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by salami738** [soligen2010/Adafruit_ADS1X15#15]
This is not a bug. I would like to say thank you for implementing additional features.
I use this library for my electronic load and it works fine (even with the purple clone board)!

You can add the STM32 bluepill board to the list of supported boards (PB7=SDA, PB6=SCL), it works fine. Link: https://wiki.stm32duino.com/index.php?title=Blue_Pill

greetings from germany

**Comment by soligen2010** [comment]
I am glad you found it useful, and congrats on the electronic load.  My
electronic load project was also the first project I did using this device
:)
