### ISSUE TITLE
SAMD21 with ADS1115

### ISSUE THREAD

**Issue by orhanyor** [soligen2010/Adafruit_ADS1X15#19]
Hello, i saw this fork in adafruit version. Looking at the ads1115 example got me confused about the extra pins. is it possible to run just with SDA/SCL pins without alert and raisevoltage pin? 
Im just looking to measure couple of batteries with voltage dividers thats all. thank you

**Comment by soligen2010** [comment]
Yes it is.  Use readADC_SingleEnded or readADC_Differential_x_x

**Comment by orhanyor** [comment]
thank you! i will try it soon
