### ISSUE TITLE
Regarding the ADS1115 and continuous mode!

### ISSUE THREAD

**Issue by xDGameStudios** [soligen2010/Adafruit_ADS1X15#5]
I wanted to know if it is possible to have continuous mode turned on, on A0 and A1 at the same time. And if not what workaround would you suggest?! I need to read data from 2 sensors with a 500Hz sample rate (as steady as possible) is a medical application project (in a beginning test stage). Thank you for your time

**Comment by soligen2010** [comment]
The chip is not capable of that. You would need to use 2 chips for that on
two different I2C addresses
